/* Interactive prototype layer. Every reading is simulated in this browser only. */
const demo={temp:29.6,humidity:51,battery:37,online:18};
const $demo=s=>document.querySelector(s);
function stamp(){return new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});}
function modal(title,content,actions){document.querySelector('.modal-shade')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal-shade" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div><div class="modal-body">${content}</div><div class="modal-foot">${actions||'<button class="button secondary" onclick="closeModal()">关闭</button>'}</div></div></div>`)}
function closeModal(){document.querySelector('.modal-shade')?.remove()}
function active(){return state.alerts.filter(a=>a.status!=='已恢复'&&a.status!=='已关闭')}
function simulate(){demo.temp=Math.max(23,Math.min(33,+(demo.temp+(Math.random()*3-1)).toFixed(1)));demo.humidity=Math.round(43+Math.random()*18);demo.battery=Math.max(25,demo.battery-Math.floor(Math.random()*3));if(demo.temp>=28&&!state.alerts.some(a=>a.id==='SIM-001'&&a.status!=='已恢复'))state.alerts.unshift({id:'SIM-001',level:demo.temp>30?'紧急':'严重',title:'机房 A 温度阈值告警',detail:`当前 ${demo.temp}℃，阈值 28℃`,time:stamp(),status:'待确认'});if(demo.temp<27.5){let a=state.alerts.find(a=>a.id==='SIM-001');if(a)a.status='已恢复'}renderDemo();toast(`模拟采集完成：${demo.temp}℃ / ${demo.humidity}%RH`)}
function confirmAlert(id){let a=state.alerts.find(a=>a.id===id);if(a){a.status='处理中';renderDemo();toast('告警已确认，已模拟发送处理通知')}}
function alertDetail(id){let a=state.alerts.find(a=>a.id===id);if(!a)return;modal('告警详情',`<div class="kv"><span>告警编号</span><b>${a.id}</b></div><div class="kv"><span>告警内容</span><b>${a.title}</b></div><div class="kv"><span>触发条件</span><span>${a.detail}</span></div><div class="kv"><span>发生时间</span><span>${a.time}</span></div><div class="kv"><span>通知记录</span><span>企业微信、飞书已发送</span></div><div class="form-row"><label>处理备注</label><textarea id="note" placeholder="例如：已安排现场检查"></textarea></div>`,a.status==='待确认'?`<button class="button secondary" onclick="closeModal()">取消</button><button class="button" onclick="confirmAlert('${id}');closeModal()">确认告警</button>`:`<button class="button" onclick="closeAlert('${id}')">保存处理记录</button>`)}
function closeAlert(id){let a=state.alerts.find(a=>a.id===id);a.status='已关闭';a.note=document.querySelector('#note').value;closeModal();renderDemo();toast('告警处理记录已保存')}
function deviceDetail(key){let data={temp:['温湿度传感器-01','环境','机房 A · 东侧',`${demo.temp} ℃`],ups:['UPS-01','动力','机房 A · 供电区',`${demo.battery}%`],door:['门禁-01','安保','机房 A · 主入口','门已关闭'],fan:['新风机-01','环境','机房 A · 西侧','设备离线']}[key];modal(data[0],`<div class="kv"><span>设备类型</span><b>${data[1]}</b></div><div class="kv"><span>安装位置</span><span>${data[2]}</span></div><div class="kv"><span>在线状态</span><span class="badge ${key==='fan'?'bad':''}">${key==='fan'?'离线':'在线'}</span></div><div class="kv"><span>当前读数</span><b>${data[3]}</b></div><div class="win-chart" style="height:130px;margin-top:16px"><div class="chart-line"></div><span style="position:absolute;left:12px;top:8px;font-size:12px">最近 24 小时模拟趋势</span></div>`,`<button class="button secondary" onclick="closeModal()">关闭</button><button class="button" onclick="simulate();closeModal()">模拟设备数据</button>`)}
function addDevice(){modal('添加模拟设备',`<div class="form-row"><label>设备名称</label><input id="newDevice" value="温湿度传感器-02"></div><div class="form-row"><label>设备类型</label><select><option>环境监测</option><option>动力设备</option><option>安保设备</option></select></div><div class="form-row"><label>所属机房</label><select><option>机房 A</option><option>机房 B</option></select></div><small style="color:#738194">仅模拟本次会话中的接入结果。</small>`,`<button class="button secondary" onclick="closeModal()">取消</button><button class="button" onclick="saveDevice()">保存并接入</button>`)}
function saveDevice(){demo.online++;closeModal();renderDemo();toast('模拟设备已接入并开始采集')}
function noticeSetting(){modal('通知策略',`<div class="form-row"><label>告警等级</label><select><option>紧急、严重</option><option>全部</option></select></div><div class="form-row"><label>通知渠道</label><span><label><input type="checkbox" checked> 企业微信</label> <label><input type="checkbox" checked> 飞书</label> <label><input type="checkbox"> 短信</label></span></div><div class="form-row"><label>重复提醒</label><select><option>每 15 分钟一次</option><option>不重复</option></select></div>`,`<button class="button secondary" onclick="closeModal()">取消</button><button class="button" onclick="closeModal();toast('通知策略已保存（模拟）')">保存</button>`)}
function badge(l){return `<span class="badge ${l==='紧急'?'bad':l==='严重'?'warn':''}">${l}</span>`}
function alertRows(){return active().map(a=>`<div class="alert-row"><i class="level ${a.level==='紧急'?'danger':''}"></i><div class="clickable" onclick="alertDetail('${a.id}')"><p>${a.title} ${badge(a.level)}</p><small>${a.detail} · ${a.time} · ${a.status}</small></div>${a.status==='待确认'?`<button class="text-button" onclick="confirmAlert('${a.id}')">确认告警</button>`:`<button class="text-button" onclick="alertDetail('${a.id}')">查看详情</button>`}</div>`).join('')}
function overview(){return `<div class="page-title"><div><h1>运行总览</h1><p>上海 · 浦东数据中心　/　机房 A</p></div><div class="demo-toolbar"><span class="sim-pill">模拟数据 · ${stamp()}</span><button class="button" onclick="simulate()">↻ 采集一组模拟数据</button></div></div><div class="metrics"><div class="metric ok clickable" onclick="showPage('devices')"><span class="label">在线设备</span><b>${demo.online}<small>/ 19</small></b><small>点击查看设备</small></div><div class="metric alert clickable" onclick="showPage('alerts')"><span class="label">当前告警</span><b>${active().length}</b><small>点击处理告警</small></div><div class="metric clickable" onclick="deviceDetail('temp')"><span class="label">机房温度</span><b>${demo.temp}℃</b><small style="color:#cb8215">点击查看趋势</small></div><div class="metric clickable" onclick="deviceDetail('ups')"><span class="label">UPS 电池容量</span><b>${demo.battery}%</b><small style="color:#d9564d">点击查看设备</small></div></div><div class="room-grid"><div class="panel room"><div class="panel-head"><h2>机房设备状态</h2><button class="text-button" onclick="showPage('devices')">查看设备 →</button></div><div class="room-map"><span class="map-label">机房 A · 3F</span><div class="rack" style="left:25%;top:60px"></div><div class="rack" style="left:52%;top:60px"></div><button class="sensor bad" style="left:14%;top:45px" onclick="deviceDetail('temp')">🌡</button><button class="sensor" style="left:78%;top:60px" onclick="deviceDetail('ups')">⚡</button><button class="sensor" style="left:79%;top:154px" onclick="deviceDetail('door')">▣</button></div></div><div class="panel"><div class="panel-head"><h2>重点状态</h2><button class="text-button" onclick="simulate()">刷新数据</button></div><div class="status-list"><div class="status-row clickable" onclick="deviceDetail('temp')"><span>机房温度</span><b style="color:#d9564d">${demo.temp}℃</b></div><div class="status-row clickable" onclick="deviceDetail('ups')"><span>UPS-01 电池</span><b style="color:#cb8215">${demo.battery}%</b></div><div class="status-row clickable" onclick="deviceDetail('door')"><span>门禁状态</span><b>关闭</b></div></div></div></div><div class="panel"><div class="panel-head"><h2>待处置告警</h2><button class="text-button" onclick="showPage('alerts')">查看全部 →</button></div><div class="alerts">${alertRows()||'<p style="padding:16px;color:#738194">暂无待处理告警</p>'}</div></div>`}
function alerts(){return `<div class="page-title"><div><h1>告警中心</h1><p>查看、确认并记录每一条异常的处置过程</p></div><div class="demo-toolbar"><button class="button secondary" onclick="modal('筛选告警','<div class=\'form-row\'><label>告警等级</label><select><option>全部等级</option><option>紧急</option><option>严重</option></select></div>','<button class=\'button\' onclick=\'closeModal();toast(\"已应用筛选（模拟）\")\'>应用</button>')">筛选 ▾</button><button class="button" onclick="simulate()">模拟新数据</button></div></div><div class="panel"><table class="device-table"><thead><tr><th>告警内容</th><th>等级</th><th>发生时间</th><th>状态</th><th>操作</th></tr></thead><tbody>${state.alerts.map(a=>`<tr class="clickable" onclick="alertDetail('${a.id}')"><td><b>${a.title}</b><br><small>${a.detail}</small></td><td>${badge(a.level)}</td><td>${a.time}</td><td>${a.status}</td><td onclick="event.stopPropagation()"><button class="text-button" onclick="alertDetail('${a.id}')">详情</button></td></tr>`).join('')}</tbody></table></div>`}
function devices(){let rows=[['temp','温湿度传感器-01','环境',`温度 ${demo.temp}℃`],['ups','UPS-01','动力',`电池 ${demo.battery}%`],['door','门禁-01','安保','门已关闭'],['fan','新风机-01','环境','设备离线']];return `<div class="page-title"><div><h1>设备与机房</h1><p>19 台设备 · 58 个监控点</p></div><div class="demo-toolbar"><button class="button secondary" onclick="simulate()">刷新全部数据</button><button class="button" onclick="addDevice()">+ 添加设备</button></div></div><div class="panel"><table class="device-table"><thead><tr><th>设备名称</th><th>类型</th><th>关键状态</th><th>最后上报</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr class="clickable" onclick="deviceDetail('${r[0]}')"><td><b>${r[1]}</b><br><small>机房 A</small></td><td>${r[2]}</td><td>${r[3]}</td><td>刚刚</td><td><button class="text-button">详情</button></td></tr>`).join('')}</tbody></table></div>`}
function reports(){return `<div class="page-title"><div><h1>趋势与报表</h1><p>温湿度传感器-01 · 最近 24 小时</p></div><div class="demo-toolbar"><button class="button secondary" onclick="toast('已模拟导出 CSV 文件')">导出 CSV</button><button class="button" onclick="simulate()">刷新趋势数据</button></div></div><div class="panel" style="padding:18px"><div class="win-chart" style="height:290px"><div class="chart-line"></div><span style="position:absolute;right:14px;top:12px;color:#d9564d">当前 ${demo.temp}℃ / ${demo.humidity}%RH</span></div></div>`}
function settings(){return `<div class="page-title"><div><h1>配置中心</h1><p>管理阈值、通知与权限</p></div><button class="button" onclick="noticeSetting()">编辑通知策略</button></div><div class="panel"><div class="status-list"><div class="status-row clickable" onclick="modal('温度阈值规则','<div class=\'form-row\'><label>触发条件</label><input value=\'温度 ≥ 28℃ 持续 5 分钟\'></div>','<button class=\'button\' onclick=\'closeModal();toast(\"阈值规则已保存（模拟）\")\'>保存</button>')"><span><b>温度过高</b><br><small>温度 ≥ 28℃ 持续 5 分钟</small></span><span class="badge warn">严重</span></div><div class="status-row clickable" onclick="deviceDetail('ups')"><span><b>UPS 电池容量低</b><br><small>容量 ≤ 40% 持续 3 分钟</small></span><span class="badge bad">紧急</span></div><div class="status-row clickable" onclick="noticeSetting()"><span><b>通知策略</b><br><small>企业微信、飞书、短信</small></span><button class="text-button">编辑</button></div></div></div>`}
function renderDemo(){renderWeb();renderMobile();renderMini();renderWindows()}
function renderMobile(){document.querySelector('#mobile').innerHTML=`<div class="mobile-frame"><div class="mobile-top"><small>上海 · 浦东数据中心</small><h1>早上好，王工</h1><small>更新于 ${stamp()}</small></div><div class="mobile-body"><button class="button" style="width:100%" onclick="simulate()">↻ 现场刷新模拟数据</button><div class="mobile-summary" style="margin-top:10px"><div class="mobile-card clickable" onclick="showPage('alerts');document.querySelector('[data-view=web]').click()">当前告警<b style="color:#d9564d">${active().length}</b></div><div class="mobile-card clickable" onclick="deviceDetail('temp')">机房温度<b>${demo.temp}℃</b></div></div><div class="mobile-section">需要关注</div>${active().slice(0,2).map(a=>`<div class="mobile-card clickable" onclick="alertDetail('${a.id}')" style="margin-bottom:9px"><b>${a.title}</b><br><small>${a.status}</small></div>`).join('')}</div><div class="mobile-nav"><span class="active">▦<br>首页</span><span onclick="showPage('alerts');document.querySelector('[data-view=web]').click()">⚠<br>告警</span><span onclick="showPage('devices');document.querySelector('[data-view=web]').click()">▣<br>设备</span><span onclick="noticeSetting()">我<br>的</span></div></div>`}
function renderMini(){document.querySelector('#mini').innerHTML=`<div class="mini-frame"><div class="mini-top">EzDAQ EPS</div><div class="mini-body"><div class="mini-overview clickable" onclick="showPage('alerts');document.querySelector('[data-view=web]').click()"><small>浦东数据中心</small><b>${active().length} 条待处理告警</b><small>点击处理现场异常</small></div><button class="button" style="margin-top:13px;width:100%" onclick="simulate()">模拟现场刷新</button><div class="mobile-section">快捷查看</div><div class="mobile-summary"><div class="mobile-card clickable" onclick="deviceDetail('temp')">环境<br><b>${demo.temp}℃</b></div><div class="mobile-card clickable" onclick="deviceDetail('ups')">动力<br><b>${demo.battery}%</b></div></div><div class="mini-list">${active().map(a=>`<div class="status-row clickable" onclick="alertDetail('${a.id}')"><span>${a.title}</span>${badge(a.level)}</div>`).join('')}</div></div></div>`}
function renderWindows(){document.querySelector('#windows').innerHTML=`<div class="windows-shell"><div class="win-title">EzDAQ EPS 上位机监控中心 <span style="float:right">—　□　×</span></div><div class="win-menu">文件　监控　告警　报表 <button class="text-button" style="float:right" onclick="simulate()">刷新模拟数据</button></div><div class="win-content"><aside class="win-tree"><b>监控站点</b><p class="active clickable" onclick="showPage('overview');document.querySelector('[data-view=web]').click()">▣ 浦东数据中心</p><p class="clickable" onclick="deviceDetail('temp')">　▣ 机房 A</p></aside><section class="win-panel"><h3>浦东数据中心 · 实时监控</h3><div class="win-stats"><div class="win-stat">在线设备<b>${demo.online}/19</b></div><div class="win-stat">当前告警<b>${active().length}</b></div><div class="win-stat">机房温度<b>${demo.temp}℃</b></div><div class="win-stat">UPS 电池<b>${demo.battery}%</b></div></div><div class="win-chart"><div class="chart-line"></div></div>${alertRows()}</section></div></div>`}
renderDemo();
